In [1]:
import sys
sys.executable


'/home/ivankova/miniconda3/envs/ml-zoomcamp/bin/python'

In [2]:
import pandas as pd

df = pd.read_csv("car_fuel_efficiency.csv")
df.head()          # посмотреть таблицу


engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [3]:
import pandas as pd
pd.__version__


'2.3.2'

In [4]:
import pandas as pd

# Загружаем данные
df = pd.read_csv("car_fuel_efficiency.csv")

# Количество строк
len(df)


9704

In [6]:
df["fuel_type"].unique()      # посмотрим, какие именно значения встречаются
df["fuel_type"].nunique()     # сколько их всего


2

In [7]:
df["fuel_type"].unique()   

array(['Gasoline', 'Diesel'], dtype=object)

In [13]:
missing_per_column = df.isna().sum()
missing_per_column

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [14]:
df.loc[df["origin"] == "Asia", "fuel_efficiency_mpg"].max()

23.759122836520497

In [15]:
df["horsepower"].median()

149.0

In [16]:
df["horsepower"].mode()[0]

np.float64(152.0)

In [17]:
df["horsepower"].fillna(152.0, inplace=True)
df["horsepower"].median()

/tmp/ipykernel_339853/1942345368.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["horsepower"].fillna(152.0, inplace=True)


152.0

In [18]:
import numpy as np

asia = df[df["origin"] == "Asia"].copy()
len(asia), asia.head(3)

(3247,
     engine_displacement  num_cylinders  horsepower  vehicle_weight  \
 8                   250            1.0       174.0     2714.219310   
 12                  320            5.0       145.0     2783.868974   
 14                  200            6.0       160.0     3582.687368   
 
     acceleration  model_year origin fuel_type         drivetrain  num_doors  \
 8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
 12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
 14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
 
     fuel_efficiency_mpg  
 8             16.823554  
 12            16.175820  
 14            11.871091  )

In [19]:
X_df = asia[["vehicle_weight", "model_year"]].head(7)
X_df

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [20]:
X = X_df.values
X.shape, X[:3] 

((7, 2),
 array([[2714.21930965, 2016.        ],
        [2783.86897424, 2010.        ],
        [3582.68736772, 2007.        ]]))

In [21]:
XTX = X.T @ X
XTX, XTX.shape


(array([[62248334.33150762, 41431216.5073268 ],
        [41431216.5073268 , 28373339.        ]]),
 (2, 2))

In [22]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [23]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y.shape, y


((7,), array([1100, 1300,  800,  900, 1000, 1100, 1200]))

In [24]:
w = XTX_inv @ X.T @ y
w, w.shape



(array([0.01386421, 0.5049067 ]), (2,))

In [25]:
w.sum()


np.float64(0.5187709081074007)